credentials:
  usernames:
    student1:
      email: samuel.wehrli@gmail.com
      name: Samuel Wehrli
      password: $2b$12$UtIMHvsQIJBX/BEsALu5q.WfNcXI/CpdDl3Yzcb7rn2u4NthygqrW # To be replaced with hashed password
    guest:
      name: Gast
      password: $2b$12$eJs.tngJrmeYayLV6tU1tO85R3JO70t5mOZZPpS9L3ygF0Xs1yo1u # To be replaced with hashed password
cookie:
  expiry_days: 30  # number of days until password is asked again
  key: JgDyEoKUNItM5prxo194jDeLYzVzmYE6 # Must be string, use https://randomkeygen.com/
  name: streamlitcookie
